# 项目启动端口
server:
  port: 8080
# 数据库数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family_service_platform?useUnicode=true&useSSL=false
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录

# mybatis配置
mybatis:
  mapper-locations: com/msb/mapper/*.xml # mapper映射文件位置
  configuration:
    map-underscore-to-camel-case: true   # 驼峰命名
# sql日志输出层
logging:
  level:
    com:
      msb:
        mapper: debug
